ProjectVersion001/Models/RoomAllocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjectVersion001.Models
{
    public class RoomAllocation
    {
        public int Id { set; get; }

        [Required(ErrorMessage = "Department can't be empty")]
        public int DepartmentId { set; get; }
        public virtual Department Department { set; get; }

        [Required(ErrorMessage = "Course can't be empty")]
        public int CourseId { set; get; }
        public virtual Course Course { set; get; }

        [Required(ErrorMessage = "Room can't be empty")]
        public int RoomId { set; get; }
        public virtual Room Room { set; get; }

        [Required(ErrorMessage = "Day can't be empty")]
        public int DayId { set; get; }
        public virtual Day Day { set; get; }
        [Required(ErrorMessage = "Start time is required")]
        [Display(Name = "Start time (Formate HH:MM) (24 Hours)")]
        public string StartTime { set; get; }
        [Required(ErrorMessage = "End time is required")]
        [Display(Name = "End time (Formate HH:MM) (24 Hours)")]
        public string EndTime { set; get; }


    }
}

ProjectVersion001/Controllers/RoomAllocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectVersion001.Models;

namespace DepartmentMVC.Controllers
{
    public class RoomAllocationController : Controller
    {
        private UniversityDbContex db = new UniversityDbContex();

        //
        // GET: /RoomAllocation/

        public ActionResult Index()
        {
            var roomallocations = db.RoomAllocations.Include(r => r.Department).Include(r => r.Course).Include(r => r.Room).Include(r => r.Day);
            return View(roomallocations.ToList());
        }

        //
        // GET: /RoomAllocation/Details/5

        public ActionResult Details(int id = 0)
        {
            RoomAllocation roomallocation = db.RoomAllocations.Find(id);
            if (roomallocation == null)
            {
                return HttpNotFound();
            }
            return View(roomallocation);
        }

        //
        // GET: /RoomAllocation/Create

        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
            ViewBag.CourseId = new SelectList("", "CourseId", "Code");
            ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name");
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Name");
            return View();
        }

        //
        // POST: /RoomAllocation/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomAllocation roomallocation)
        {

            Room room = db.Rooms.Find(roomallocation.RoomId);
            Course course = db.Courses.Find(roomallocation.CourseId);
            Day day = db.Days.Find(roomallocation.DayId);

           
            if (ModelState.IsValid)
            {
               
                int givenfrom, givenEnd;

                try
                {
                    givenfrom = ConvertTimetoInt(roomallocation.StartTime);
                }
                catch (Exception anException)
                {
                    if (TempData["ErrorMessage3"] == null)
                    {
                        TempData["ErrorMessage1"] = anException.Message;
                    }
                    TempData["ErrorMessage4"] = TempData["ErrorMessage3"];
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                    
                }

                try
                {
                    givenEnd = ConvertTimetoInt(roomallocation.EndTime);
                }
                catch (Exception anException)
                {
                    if (TempData["ErrorMessage3"] == null)
                    {
                        TempData["ErrorMessage2"] = anException.Message;
                    }
                    TempData["ErrorMessage5"] = TempData["ErrorMessage3"];
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }

                if (givenEnd < givenfrom)
                {
                    TempData["Message"] = "Class Should Start Before End (24 hours)";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }
                if (givenEnd == givenfrom)
                {
                    TempData["Message"] = "Class Should Start Before End (24 hours)";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }

                if ((givenfrom < 0) || (givenEnd >= (24*60)))
                {
                    TempData["Message"] = " 24 hours--format HH:MM";
                    ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                    ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                    ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                    ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                    return View(roomallocation);
                }

                    List<RoomAllocation> overLapList=new List<RoomAllocation>();

                    var DayRoomAllocationList =
                    db.RoomAllocations.Include(c => c.Course).Include(d =>d.Day).Include(r => r.Room).Where(r => r.RoomId == roomallocation.RoomId && r.DayId == roomallocation.DayId)
                        .ToList();

                    foreach (var aDayroomAllocation in DayRoomAllocationList)
                    {
                        //int OverlapFrom = 0;
                        //int OverlapEnd = 0;
                        //RoomAllocation overlap =new RoomAllocation();

                        int DbFrom = ConvertTimetoInt(aDayroomAllocation.StartTime);                        
                        int DbEnd =  ConvertTimetoInt(aDayroomAllocation.EndTime);
                      
                        if (
                                ((DbFrom <= givenfrom) && (givenfrom < DbEnd))
                                || ((DbFrom < givenEnd) && (givenEnd <= DbEnd))
                                || ((givenfrom <= DbFrom) && (DbEnd <= givenEnd))
                            )
                        {
                            overLapList.Add(aDayroomAllocation);
                        }
                        
                    }
                    if (overLapList.Count == 0)
                    {
                      
                        db.RoomAllocations.Add(roomallocation);
                        db.SaveChanges();
                        TempData["Message"] = "Room : " + room.Name + "Allocated "
                        + " for course : " + course.Code + " From " + roomallocation.StartTime
                        + " to " + roomallocation.EndTime + " on " + day.Name;
                    }
                    else
                    {
                        string message = "Room : " + room.Name + " Overlapped With : ";
                        foreach (var anOverlappedRoom in overLapList)
                        {
                            int dbFrom = ConvertTimetoInt(anOverlappedRoom.StartTime);
                            int dbEnd = ConvertTimetoInt(anOverlappedRoom.EndTime);

                            string overlapStart, overlapEnd;

                            if ((dbFrom <= givenfrom) && (givenfrom < dbEnd))
                                overlapStart = roomallocation.StartTime;
                            else
                                overlapStart = anOverlappedRoom.StartTime;

                            if ((dbFrom < givenEnd) && (givenEnd <= dbEnd))
                                overlapEnd = roomallocation.EndTime;
                            else
                                overlapEnd = anOverlappedRoom.EndTime;
                            message += " Course : " + anOverlappedRoom.Course.Code + " Start Time : "
                                + anOverlappedRoom.StartTime + " End Time : "
                                + anOverlappedRoom.EndTime + " Overlapped from : ";
                            message += overlapStart + " To " + overlapEnd;
                        }

                        TempData["Message"] = message + " on " + day.Name ;

                        ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code");
                        ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Code", course.DepartmentId);
                        ViewBag.CourseId = new SelectList(db.Courses.Where(c => c.DepartmentId == course.DepartmentId), "CourseId", "Code", roomallocation.CourseId);
                        ViewBag.RoomId = new SelectList(db.Rooms, "RoomId", "Name", roomallocation.RoomId);
                        ViewBag.DayId = new SelectList(db.Days, "DayId", "Name", roomallocation.DayId);
                        return View(roomallocation);
                    }
                //}
                

ProjectVersion001/Views/Shared/_CourseInfo.cshtml
@using System.Web.Mvc.Html
<div id="CourseInfo">
    <table>
        <tr>
            <td>Code: </td>
            <td>@ViewBag.Code</td>
        </tr>
        <tr>
            <td>Credit: </td>
            <td>@ViewBag.Credit</td>
        </tr>

    </table>
</div>

ProjectVersion001/Views/Shared/_CourseStatus.cshtml
@using System.Activities.Expressions
@model IEnumerable<ProjectVersion001.Models.Course>

@if (Model != null)
{
    <table class="table table-striped">
        <tr>
            <th>
                Course Code
            </th>
            <th>
                Course Name
            </th>
            <th>
                Semester
            </th>
            <th>
                Assigned To
            </th>

        </tr>

        @foreach (var item in Model)
        {
            
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CourseSemister.Semistername)
                </td>
                <td>
                    @if (item.AssignTo != null) 
                    { 
                        @Html.DisplayFor(modelItem => item.AssignTo)
                    }
                    @if (item.AssignTo == null)
                    {
                        item.AssignTo = "Not Assigned";
                        @Html.DisplayFor(modelItem => item.AssignTo) 
                    }
                </td>

            </tr>
        }
    </table>
}



<div style="color: darkgoldenrod"><h3>@ViewBag.NotAssigned</h3></div>

ProjectVersion001/Views/Shared/_FillteredTeacher.cshtml
@if(ViewBag.TeacherId!=null)
{    
    @Html.DropDownList("TeacherId", string.Empty)
    
    }

ProjectVersion001/Views/Shared/_FilteredCourse.cshtml
@if (ViewBag.CourseId != null)
{
    @Html.DropDownList("CourseId", string.Empty)
}

ProjectVersion001/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - University</title>
    <link href="~/Custom_design/Logo.css" rel="stylesheet" />
    

    <script src="~/Scripts/bootstrap.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/respond.min.js"></script>

</head>
    <body>
        
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">

           
               @*@Html.ActionLink("Ctborg University", "Index", "Home", null, new { @class = "i2Style" })*@
                @*<div class="i2Style">Cyborg Coders</div>*@
            
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink(" University", "Index", "Home", null, new { @class = "i2Style" })
                    
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Department<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Add Departments", "Create", "Department")</li>
                                <li>@Html.ActionLink("View Department", "Index", "Department")</li>

                                
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Course<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Add Course", "Create", "Courses")</li>
                                <li>@Html.ActionLink("View Course", "Index", "Courses")</li>
                                @*<li>@Html.ActionLink("Course", "Index", "Courses")</li>*@

                            </ul>
                        </li>
                    </ul>
                   
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teacher<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Add Teacher", "Create", "Teacher")</li>
                                <li>@Html.ActionLink("View Teacher", "Index", "Teacher")</li>
                                @*  <li>@Html.ActionLink("Teacher", "Index", "Teacher")</li>*@

                            </ul>
                        </li>
                    </ul>  
                   
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Assign Course<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Assign Course", "Create", "AssignCourse")</li>
                                <li>@Html.ActionLink("View Course Status", "ViewCourseStatus", "AssignCourse")</li>
                                @*           <li>@Html.ActionLink("Coursse Enrollment", "Index", "AssignCourse")</li>*@

                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                         <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Student<b class="caret"></b></a>
                             <ul class="dropdown-menu">
                                 <li>@Html.ActionLink("Add Student", "Create", "Student")</li>
                                 <li>@Html.ActionLink("View Student", "Index", "Student")</li>
                                 @*<li>li>@Html.ActionLink("Student", "Index", "Student")</li></li>*@

                             </ul>
                         </li>
                     </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Class Room<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Allocate Room", "Create", "RoomAllocation")</li>
                                <li>@Html.ActionLink("Room States", "RoomAllocationView", "RoomAllocation")</li>
                                @*  li>@Html.ActionLink("Room Alocation", "Index", "RoomAllocation")</li>*@

                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Enroll Course<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Add Course", "Create", "EnrollCourse")</li>
                                <li>@Html.ActionLink("View Status", "Index", "EnrollCourse")</li>
                                @*  li>@Html.ActionLink("Room Alocation", "Index", "RoomAllocation")</li>*@

                            </ul>
                        </li>
                    </ul>
              
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Result<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Result Enrty", "Create", "ResultEntry")</li>
                                <li>@Html.ActionLink("View Result", "ViewResult", "ResultEntry")</li>
                                @*  li>@Html.ActionLink("Room Alocation", "Index", "RoomAllocation")</li>*@

                            </ul>
                        </li>
                    </ul>
                            
         
                            

                        
                    @*@Html.Partial("_LoginPartial")*@
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

   
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

ProjectVersion001/Views/Shared/_ResultInformation.cshtml
@model List<ProjectVersion001.Models.EnrollCourse>
           
@if (Model != null)
{
    <table class="table table-striped">
        <tr>
            <th>
                Course Code
            </th>
            <th>
                Course Name
            </th>
            <th>
                Grade
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Course.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>

                <td>
                    @if (item.GradeName != null)
                    {
                         @Html.DisplayFor(modelItem => item.GradeName)
                    }
                    @if (item.GradeName == null)
                    {
                        item.GradeName = "Empty";
                        @Html.DisplayFor(modelItem => item.GradeName)
                    }
                    
                </td>

            </tr>
        }

    </table>
}

<div style="color: darkgoldenrod"><h3>@ViewBag.NotEnrolled</h3></div>

ProjectVersion001/Views/Shared/_RoomAllocationView.cshtml
@model IEnumerable<ProjectVersion001.Models.Course>

<table class="table table-striped">
    <tr>
        <th>
            Course Code
        </th>
        <th>
            Name/Title
        </th>
        <th>
            Schedule Info
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var anAllocatedRoom in item.RoomAllocationList)
                {
                    <b>Room:</b>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.Room.Name)
                    <i>,</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.Day.Name)
                    <i>,</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.StartTime)
                    <i>-</i>
                    @Html.DisplayFor(modelItem => anAllocatedRoom.EndTime)
                    <b><i>;</i></b>
                }
                @if (item.RoomAllocationList.Count == 0)
                {
                    <i>Unscheduled</i>
                }
            </td>

        </tr>
    }

</table>
<div style="color: darkgoldenrod"><h3>@ViewBag.NoCourse</h3></div>

ProjectVersion001/Views/Shared/_StudentInformation.cshtml
@using System.Web.Mvc.Html
<div id="StudentInfo">
    <table>
        <tr>
            <td>Name: </td>
            <td>@ViewBag.Name</td>
        </tr>
        <tr>
            <td>Email: </td>
            <td>@ViewBag.Email</td>
        </tr>
        <tr>
            <td>Department:  </td>
            <td>@ViewBag.Dept</td>
        </tr>
    </table>
</div>

ProjectVersion001/Views/Shared/_TeachersCreditInfo.cshtml
@using System.Web.Mvc.Html
<div id="TeacherInfo">
    <table>
        <tr>
            <td>Credit to be taken: </td>
            <td>@ViewBag.Credit</td>
        </tr>
        <tr>
            <td>Remaining Credit: </td>
            <td>@ViewBag.RemainingCredit</td>
        </tr>
        
    </table>
</div>